### ISSUE TITLE
Enabling "Affixes" causes multiple issues

### ISSUE THREAD

**Issue by filliph** [Jodsderechte/DungeonAuraTools#27]
Every time I /reload, the message 

> DungeonAuraTools: Enabled Auras that havn't been Exported detected. Please export them via /Dat export 

Shows up three times. It tries to update the Legion auras:

![image](https://user-images.githubusercontent.com/9424286/198247246-d113d1dd-7b0c-4a98-a1e4-94b31b51c316.png)

And spams the chat log with:

![image](https://user-images.githubusercontent.com/9424286/198247367-8a5a189d-5cd6-4fcb-970d-bfb4046e3360.png)

Then it prints "Affixes" twice, and produces this Lua error:

```
1x Interface/AddOns/DungeonAuraTools/Export.lua:96: attempt to concatenate local 'Spellname' (a nil value)
[string "@Interface/AddOns/DungeonAuraTools/Export.lua"]:96: in function `buildAura'
[string "@Interface/AddOns/DungeonAuraTools/Export.lua"]:47: in function `buildDataToExport'
[string "@Interface/AddOns/DungeonAuraTools/Export.lua"]:12: in function `callbackFunc'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:1979: in function `Close'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:1659: in function `ImportImpl'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:1479: in function <...ace/AddOns/WeakAurasOptions/OptionsFrames/Update.lua:1478>
```

If I disable the "[PH] 10.0 Affix", I'm able to import the Affixes group.

**Comment by Jodsderechte** [comment]
oh right that happens because storming doesn't exist in the prepatch
