### ISSUE TITLE
On demand loading of dungeon auras (of sorts)

### ISSUE THREAD

**Issue by linaori** [Jodsderechte/DungeonAuraTools#29]
To reduce (re)load time of the interface, I want to have as little weak auras as possible that I don't actively use. With this addon it's already possible to remove -> import the dungeons auras really quickly whenever you want, and I need 0 configuration or customization outside of what addon provides atm.

My workflow would be:
1. Enter a dungeon
2. Get a popup if I want to import the auras for that specific dungeon
3. Do a few dungeons (repeat the process of importing)
4. Delete the auras when I'm done

I understand that a "load on demand" is not easy to implement for weak auras (maybe one day they will provide this 👀), but this flow would be really close. Additionally the current "export" button could be replaced by a more targeted import function to import a subset. This could be done based on several levels. 

User interface wise this could be a dropdown or select boxes which the export button uses to filter what is being exported.

In the most ideal scenario I'd see WeakAuras itself support pre-configured auras being added through addons, which themselves can be "load on demand", but seeing this is probably a big change for WAs, I doubt that would happen

**Comment by Jodsderechte** [comment]
I this this is a pretty nieche usecase and i won't have time to add this anytime soon. If you or someone else want's to look into implementing this a pull request would be welcome but i'll close this issue for now and maybe revisit it in the future

**Comment by Jodsderechte** [comment]
ok you win i was bored and added it anyways @linaori 😆

**Comment by linaori** [comment]
Haha, nice!
