### ISSUE TITLE
Addon Edit Features

### ISSUE THREAD

**Issue by husskhash** [Jodsderechte/DungeonAuraTools#30]
Hey, I currently download the WAs manually and edit it them each time to my own liking depending on my UI needs. This means every time I update the WAs, I have to do it again, and it takes a while cos there is so many WAs in each package.

Would be great if via the Addon, I can preset some conditions for my appearance of the dungeon packs. These would be:
Group grow (i use grid)
Group growth direction (i do left, then up)
Group row width (i use 3)
Group row space
Group column space
Group limit
Group scale
Group X Offset
Group Y Offset
Display - Hide Timer Text
Display - Show Text 1
Display - Text 1 Font Size
Display - Text 2 and 3 Font Size
Display - All fonts

If I can preset the following conditions in the addon, and it makes the groups and WAs with my conditons. I am sure other people edit them their own way too!

**Comment by CDAGaming** [comment]
At minimum, I'd like the Limit and Scale available in the addon for exporting. I personally had to still manually edit all the generated WAs to both tone down the scale and then move it due to said change

**Comment by Jodsderechte** [comment]
Would you prefer icon size or group scale? Also group x and group y offset already exists

**Comment by husskhash** [comment]
either works tbh!

**Comment by Jodsderechte** [comment]
Everything should be added for now
