### ISSUE TITLE
Adding other affixes

### ISSUE THREAD

**Issue by husskhash** [Jodsderechte/DungeonAuraTools#49]
Be nice to have the option to see how many explosive orbs are up; the shrouded affix; the thundering affix debuffs; if enemies are in sanguine;

**Comment by Jodsderechte** [comment]
shrouded is not worth since it's gone in 2 weeks thundering is already done and in the files it's just not loaded since it errors on current wow build. i can add the explosive and sanguine ones though

**Comment by Jodsderechte** [comment]
since explosive is gone in season 2 not worth adding that We'll see if adding any of the new affixes provides usefulness will close this for now
