### ISSUE TITLE
Error when sending auras to WeakAuras

### ISSUE THREAD

**Issue by Akhaim** [Jodsderechte/DungeonAuraTools#52]
### Description

WA v 5.0.5
DAT v1.0.1

It didn't happen in 0.4.1. I can't import or update the groups anymore. 

### WeakAuras Version

5.0.5

### DungeonAuraTools Version

1.0.1

### Tested with only WeakAuras and DungeonAuraTools

- [x] Yes
- [ ] No

### Lua Error

Message: ...ace/AddOns/WeakAurasOptions/OptionsFrames/Update.lua:2010: bad argument #1 to 'format' (string expected, got table)
Time: Mon Nov  7 18:41:49 2022
Count: 1
Stack: ...ace/AddOns/WeakAurasOptions/OptionsFrames/Update.lua:2010: bad argument #1 to 'format' (string expected, got table)
[string "=[C]"]: in function `format'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:2010: in function `AddBasicInformationWidgets'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:1289: in function <...ace/AddOns/WeakAurasOptions/OptionsFrames/Update.lua:1264>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/WeakAuras/Transmission.lua"]:465: in function <Interface/AddOns/WeakAuras/Transmission.lua:449>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DungeonAuraTools/Export.lua"]:14: in function `CallbackFunc'
[string "@Interface/AddOns/DungeonAuraTools/Export.lua"]:4: in function `exportAuras'
[string "@Interface/AddOns/DungeonAuraTools/Options.lua"]:11: in function <Interface/AddOns/DungeonAuraTools/Options.lua:11>
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterWardrobe/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/BetterWardrobe/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdvancedRaidFrameSettings/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...ncedRaidFrameSettings/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/AdvancedRaidFrameSettings/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/AdvancedRaidFrameSettings/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...ings/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals: <none>

### Reproduction Steps

1. Have both addons
2. Open DAT
3. Set x offset to 300
4. Press "Send to Weakauras".

Observe error

### Last Good Version

_0.4.1_

**Comment by Jodsderechte** [comment]
Fixed in v1.0.2
