### ISSUE TITLE
Lua error on login

### ISSUE THREAD

**Issue by filliph** [Jodsderechte/DungeonAuraTools#64]
### Description

After #59 was fixed, a new error has been introduced.

### WeakAuras Version

5.2.2

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

1.0.7

### Tested with only WeakAuras and DungeonAuraTools

- [X] Yes
- [ ] No

### Lua Error

```
2x DungeonAuraTools/Export.lua:177: attempt to index field 'triggerData' (a nil value)
[string "@DungeonAuraTools/Export.lua"]:177: in function `buildAura'
[string "@DungeonAuraTools/Main.lua"]:213: in function `CheckIfAuraUpdates'
[string "@DungeonAuraTools/Main.lua"]:292: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
```

### Reproduction Steps

1. Login
2. See error

### Saved Variables

[DungeonAuraTools (2).zip](https://github.com/Jodsderechte/DungeonAuraTools/files/10143539/DungeonAuraTools.2.zip)

### Last Good Version

1.0.6

**Comment by filliph** [comment]
Adding
```
if not v.triggerData then
    DevTools_Dump(v)
end
```
Directly beneath
```
JDT.buildAura = function(ExportTable,DungeonValue,BossNameValue,TypeKey,v,ExpansionValue,ExpansionKey)
```
Prints `enabled = false`.

**Comment by filliph** [comment]
The problem is these two blocks in Main.lua:

```
                                            for k,v in pairs(TypeValue) do 
   
                                                    local AuraToCheck = JDT.buildAura(ExportTable,DungeonValue,BossNameValue,TypeKey,v,ExpansionValue,ExpansionKey)  
                                                    local InstalledAura = WeakAuras.GetData(AuraToCheck.id)
                                                if v.enabled == true then 
```

```
                                for k,v in pairs(TypeValue) do 
                                    local AuraToCheck = JDT.buildAura(ExportTable,{groupName= ExpansionValue.groupName},{additionalName = ""},TypeKey,v,ExpansionValue,ExpansionKey)
                                    local InstalledAura = WeakAuras.GetData(AuraToCheck.id)
                                    if v.enabled == true then
```

I think the problem is pretty obvious 😉

**Comment by Jodsderechte** [comment]
man i tested this extensivly but missed this bug and it's only in affixes fixing this is very easy

**Comment by Jodsderechte** [comment]
I can't seem to reproduce this issue though i don't even get how trigger data could ever be nil

**Comment by filliph** [comment]
v1.0.8 does not fix the issue.

**Comment by Jodsderechte** [comment]
i finally managed to reproduce this but it feels like debugging this requires advanced knowledge of quantum physics. Adding if not v.triggerData then
    DevTools_Dump(v)
end results in nothing xD but a nil error on trigger data

**Comment by filliph** [comment]
> i finally managed to reproduce this but it feels like debugging this requires advanced knowledge of quantum physics. Adding if not v.triggerData then DevTools_Dump(v) end results in nothing xD but a nil error on trigger data

If you follow the instructions in this post: https://github.com/Jodsderechte/DungeonAuraTools/issues/64#issuecomment-1335674716 you'll see the same output I referenced in that post.

**Comment by Jodsderechte** [comment]
i did but i didn't see the same output however i found the error and hopefully fixed it

**Comment by filliph** [comment]
@Jodsderechte this has not been fixed, the line number has however shifted:

```
1x DungeonAuraTools/Export.lua:175: attempt to index field 'triggerData' (a nil value)
[string "@DungeonAuraTools/Export.lua"]:175: in function `buildAura'
[string "@DungeonAuraTools/Main.lua"]:223: in function `CheckIfAuraUpdates'
[string "@DungeonAuraTools/Main.lua"]:302: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
```

**Comment by Jodsderechte** [comment]
mad life it fixed the bug that i encountered with trigger data being nil guess i'll have to do more checking
