### ISSUE TITLE
Toggle on/off certain sounds

### ISSUE THREAD

**Issue by AgentFX** [Jodsderechte/DungeonAuraTools#84]
### Is your feature request related to a problem? Please describe.

Sometimes when I'm not playing a melee class and I don't need to look out for most tank frontals I feel like the high amount of "avoid" and "front" calls add a lot of audio noise when I don't really need them with the class I'm currently playing.

So if I want to disable every "avoid" sound I need to disable them by hand for every weak aura that has it, and I need to disable them manually every time I overwrite/update the weak aura.

### Describe the solution you'd like

It would be nice if I would be able to toggle every "avoid", "interrupt" and all the other sounds on a per sound basis.
I would like to be able to disable every "avoid" sound with one toggle in the dat settings.

**Comment by Jodsderechte** [comment]
do you mean a general toggle for all "avoid" sounds or a toggle on a per aura basis? I definitly plan to add more options but one is easier to implement than the other :D

**Comment by AgentFX** [comment]
I meant a general toggle for all "avoid" sounds at once. 

Even tho a per aura basis would work as well but that would take probably the same amount of time to toggle all "avoid" sounds as changing them manually in weak auras options.

I think both options would probably be good in the long run, for people who struggle with changing weak auras in the weak aura options themselves. 

But whatever is easier for you to implement, I just wanted to give some feedback based on my experience (which is probably somewhat niche)
